version: '3'
services:
  app:
    container_name: app-server
    image: nextcloud:15-fpm
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '9000'
    networks:
      - rede
    volumes:
      - ./dados_app:/var/www/html
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - rede
    expose:
      - '80'
      - '443'
    volumes:
      - ./dados_onlyoffice:/var/www/onlyoffice/Data
      - ./dados_onlyoffice_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - rede
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dados_app:/var/www/html
  mysql:
    container_name: mysql-server
    image: mariadb:10.4.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sua_senha
      - MYSQL_PASSWORD=sua_senha
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - rede
    volumes:
      - ./dados_mysql:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - rede
    expose:
      - '6379'

networks:
  rede:
    driver: 'bridge'
